use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct Currency {
    pub code: &'static str,
    pub name: &'static str,
    pub sub: &'static str,
}

pub const ALL: &[Currency] = &[
    Currency { code: "USD", name: "US Dollar", sub: "Dollar" },
    Currency { code: "EUR", name: "Euro", sub: "Euro" },
    Currency { code: "GBP", name: "British Pound", sub: "Pound" },
    Currency { code: "JPY", name: "Japanese Yen", sub: "Yen" },
    Currency { code: "CNY", name: "Chinese Yuan", sub: "Yuan" },
    Currency { code: "RUB", name: "Russian Ruble", sub: "Ruble" },
    Currency { code: "BYN", name: "Belarusian Ruble", sub: "Ruble" },
    Currency { code: "UAH", name: "Ukrainian Hryvnia", sub: "Hryvnia" },
    Currency { code: "KZT", name: "Kazakhstani Tenge", sub: "Tenge" },
    Currency { code: "INR", name: "Indian Rupee", sub: "Rupee" },
    Currency { code: "PKR", name: "Pakistani Rupee", sub: "Rupee" },
    Currency { code: "BDT", name: "Bangladeshi Taka", sub: "Taka" },
    Currency { code: "LKR", name: "Sri Lankan Rupee", sub: "Rupee" },
    Currency { code: "NPR", name: "Nepalese Rupee", sub: "Rupee" },
    Currency { code: "MVR", name: "Maldivian Rufiyaa", sub: "Rufiyaa" },
    Currency { code: "IDR", name: "Indonesian Rupiah", sub: "Rupiah" },
    Currency { code: "MYR", name: "Malaysian Ringgit", sub: "Ringgit" },
    Currency { code: "SGD", name: "Singapore Dollar", sub: "Dollar" },
    Currency { code: "HKD", name: "Hong Kong Dollar", sub: "Dollar" },
    Currency { code: "TWD", name: "New Taiwan Dollar", sub: "Dollar" },
    Currency { code: "KRW", name: "South Korean Won", sub: "Won" },
    Currency { code: "THB", name: "Thai Baht", sub: "Baht" },
    Currency { code: "VND", name: "Vietnamese Dong", sub: "Dong" },
    Currency { code: "PHP", name: "Philippine Peso", sub: "Peso" },
    Currency { code: "BRL", name: "Brazilian Real", sub: "Real" },
    Currency { code: "ARS", name: "Argentine Peso", sub: "Peso" },
    Currency { code: "CLP", name: "Chilean Peso", sub: "Peso" },
    Currency { code: "COP", name: "Colombian Peso", sub: "Peso" },
    Currency { code: "PEN", name: "Peruvian Sol", sub: "Sol" },
    Currency { code: "VES", name: "Venezuelan Bolivar", sub: "Bolivar" },
    Currency { code: "MXN", name: "Mexican Peso", sub: "Peso" },
    Currency { code: "CAD", name: "Canadian Dollar", sub: "Dollar" },
    Currency { code: "AUD", name: "Australian Dollar", sub: "Dollar" },
    Currency { code: "NZD", name: "New Zealand Dollar", sub: "Dollar" },
    Currency { code: "CHF", name: "Swiss Franc", sub: "Franc" },
    Currency { code: "SEK", name: "Swedish Krona", sub: "Krona" },
    Currency { code: "NOK", name: "Norwegian Krone", sub: "Krone" },
    Currency { code: "DKK", name: "Danish Krone", sub: "Krone" },
    Currency { code: "ISK", name: "Icelandic Krona", sub: "Krona" },
    Currency { code: "PLN", name: "Polish Zloty", sub: "Zloty" },
    Currency { code: "CZK", name: "Czech Koruna", sub: "Koruna" },
    Currency { code: "HUF", name: "Hungarian Forint", sub: "Forint" },
    Currency { code: "RON", name: "Romanian Leu", sub: "Leu" },
    Currency { code: "BGN", name: "Bulgarian Lev", sub: "Lev" },
    Currency { code: "TRY", name: "Turkish Lira", sub: "Lira" },
    Currency { code: "ILS", name: "Israeli New Shekel", sub: "Shekel" },
    Currency { code: "AED", name: "UAE Dirham", sub: "Dirham" },
    Currency { code: "SAR", name: "Saudi Riyal", sub: "Riyal" },
    Currency { code: "QAR", name: "Qatari Riyal", sub: "Riyal" },
    Currency { code: "KWD", name: "Kuwaiti Dinar", sub: "Dinar" },
    Currency { code: "BHD", name: "Bahraini Dinar", sub: "Dinar" },
    Currency { code: "OMR", name: "Omani Rial", sub: "Rial" },
    Currency { code: "JOD", name: "Jordanian Dinar", sub: "Dinar" },
    Currency { code: "LBP", name: "Lebanese Pound", sub: "Pound" },
    Currency { code: "IQD", name: "Iraqi Dinar", sub: "Dinar" },
    Currency { code: "IRR", name: "Iranian Rial", sub: "Rial" },
    Currency { code: "AFN", name: "Afghan Afghani", sub: "Afghani" },
    Currency { code: "MMK", name: "Myanmar Kyat", sub: "Kyat" },
    Currency { code: "EGP", name: "Egyptian Pound", sub: "Pound" },
    Currency { code: "ZAR", name: "South African Rand", sub: "Rand" },
    Currency { code: "NGN", name: "Nigerian Naira", sub: "Naira" },
    Currency { code: "KES", name: "Kenyan Shilling", sub: "Shilling" },
    Currency { code: "MAD", name: "Moroccan Dirham", sub: "Dirham" },
    Currency { code: "DZD", name: "Algerian Dinar", sub: "Dinar" },
    Currency { code: "TND", name: "Tunisian Dinar", sub: "Dinar" },
    Currency { code: "GHS", name: "Ghanaian Cedi", sub: "Cedi" },
    Currency { code: "ETB", name: "Ethiopian Birr", sub: "Birr" },
    Currency { code: "UGX", name: "Ugandan Shilling", sub: "Shilling" },
    Currency { code: "TZS", name: "Tanzanian Shilling", sub: "Shilling" },
    Currency { code: "AZN", name: "Azerbaijani Manat", sub: "Manat" },
    Currency { code: "GEL", name: "Georgian Lari", sub: "Lari" },
    Currency { code: "AMD", name: "Armenian Dram", sub: "Dram" },
    Currency { code: "MDL", name: "Moldovan Leu", sub: "Leu" },
    Currency { code: "MKD", name: "Macedonian Denar", sub: "Denar" },
    Currency { code: "RSD", name: "Serbian Dinar", sub: "Dinar" },
    Currency { code: "HRK", name: "Croatian Kuna", sub: "Kuna" },
    Currency { code: "BAM", name: "Bosnian Convertible Mark", sub: "Mark" },
    Currency { code: "ALL", name: "Albanian Lek", sub: "Lek" },
    Currency { code: "MNT", name: "Mongolian Tugrik", sub: "Tugrik" },
    Currency { code: "KGS", name: "Kyrgyzstani Som", sub: "Som" },
    Currency { code: "TJS", name: "Tajikistani Somoni", sub: "Somoni" },
    Currency { code: "UZS", name: "Uzbekistani Som", sub: "Som" },
    Currency { code: "TMT", name: "Turkmenistani Manat", sub: "Manat" },
    Currency { code: "XAF", name: "CFA Franc (BEAC)", sub: "Franc" },
    Currency { code: "XOF", name: "CFA Franc (BCEAO)", sub: "Franc" },
    Currency { code: "XCD", name: "East Caribbean Dollar", sub: "Dollar" },
    Currency { code: "JMD", name: "Jamaican Dollar", sub: "Dollar" },
    Currency { code: "TTD", name: "Trinidad and Tobago Dollar", sub: "Dollar" },
    Currency { code: "BBD", name: "Barbadian Dollar", sub: "Dollar" },
    Currency { code: "BSD", name: "Bahamian Dollar", sub: "Dollar" },
    Currency { code: "BZD", name: "Belize Dollar", sub: "Dollar" },
    Currency { code: "GYD", name: "Guyanese Dollar", sub: "Dollar" },
    Currency { code: "SRD", name: "Surinamese Dollar", sub: "Dollar" },
    Currency { code: "HTG", name: "Haitian Gourde", sub: "Gourde" },
    Currency { code: "CUC", name: "Cuban Convertible Peso", sub: "Peso" },
    Currency { code: "CUP", name: "Cuban Peso", sub: "Peso" },
    Currency { code: "DOP", name: "Dominican Peso", sub: "Peso" },
    Currency { code: "GTQ", name: "Guatemalan Quetzal", sub: "Quetzal" },
    Currency { code: "HNL", name: "Honduran Lempira", sub: "Lempira" },
    Currency { code: "NIO", name: "Nicaraguan Cordoba", sub: "Cordoba" },
    Currency { code: "CRC", name: "Costa Rican Colon", sub: "Colon" },
    Currency { code: "PAB", name: "Panamanian Balboa", sub: "Balboa" },
    Currency { code: "PYG", name: "Paraguayan Guarani", sub: "Guarani" },
    Currency { code: "BOB", name: "Bolivian Boliviano", sub: "Boliviano" },
    Currency { code: "UYU", name: "Uruguayan Peso", sub: "Peso" },
    Currency { code: "FJD", name: "Fijian Dollar", sub: "Dollar" },
    Currency { code: "PGK", name: "Papua New Guinean Kina", sub: "Kina" },
    Currency { code: "SBD", name: "Solomon Islands Dollar", sub: "Dollar" },
    Currency { code: "WST", name: "Samoan Tala", sub: "Tala" },
    Currency { code: "TOP", name: "Tongan Pa\u{2018}anga", sub: "Pa\u{2018}anga" },
    Currency { code: "VUV", name: "Vanuatu Vatu", sub: "Vatu" },
    Currency { code: "BTC", name: "Bitcoin", sub: "BTC" },
    Currency { code: "ETH", name: "Ether", sub: "ETH" },
];

pub fn find(code: &str) -> Option<&'static Currency> {
    ALL.iter().find(|c| c.code.eq_ignore_ascii_case(code))
}